ta_advice =
[{"topic":["Meta"],"author":"Alyssa Porto","text":"After reading through the “Advice from Previous TAs” page on the CS 2910 website, I assumed I had it all figured out. Don’t hang out in stacks, don’t take it personally when students are rude, and don’t be afraid to tell people you’re not able to help when you are not holding office hours. I did not realize, no matter how useful the advice is, being a TA really requires you to go experience things yourself in order to actually know how to handle or react to a situation.\n\nNo matter how much I looked through past TA advice, I found myself constantly ignoring it as well. Each time something unexpected happened, I didn’t know how to react, even though others had told me how to. This is because, while I expected it to be something I could completely prepare for, TAing is completely a learning experience.","votes":0}
,{"topic":["Meta"],"author":"Devon Yi","text":"Reading the “Advice from Previous TAs” page all in one sitting was helpful, but at the same time, created anxiety about everything that could possibly go wrong and about what potential problems I would have to face with students. I could’ve just been lucky, but didn’t face nearly as many difficulties I thought I would.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"wording from Divya Bhaskara; idea echoed by many TAs","text":"I can honestly say that TAing has been the most rewarding aspect of my academic life.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Leila Kouame","text":"I received a lot of advice on what to do and what to avoid and while every piece of advice served as a helpful tool in doing my job, the advice only truly made sense to me after I had experienced a variety of situations.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Nicholas Langemeier","text":"I wish I had known these tips going into my TA experience, but even if I had known them I probably wouldn't have been able to use them right away.  I had to learn by doing.  Take all the lessons given by professors and other TAs and apply them, but also be flexible in your approach to TAing.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Emily Zhou","text":"Being a TA was harder work than I thought it would be.  I knew getting the new course material down would be tough, but I wasn't prepared for unprofessional students and took things too personally.\n\nThe best support system you have is your fellow TAs, and as long as you get prepared in advance and have your students' best interest in mind, it will be a great experience for you and the students both.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"John Weber","text":"Not all students are going to be friendly with you.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Caroline McNichols","text":"I had no idea how much disrespect TAs get. I've been in line at the Pav and heard other students in line going on and on about how dumb CS TAs are and that they don’t know anything. It seems they forget that TAs are all real people who live normal lives in the same community as them.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Chiara Sauvage","text":"For many of the kids in the class, this class was just a requirement they had to get through and they had no further interest. It made it more difficult to teach them because they just weren’t interested.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Chiara Sauvage","text":"Some days are not be as fun as others. Some days, everyone is installing a new package and 20 people are having issues and they’re all different and you don’t understand any of them. Some days, all the students are taking a test and your job is to walk around quietly and stare at them; you hope something interesting happens, but also hope nothing happens and everyone does great on the test without cheating.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Lisa Nguyen","text":"One thing I really wish I had known before coming a teacher assistant was how to really **teach**. I used to underestimate the role of a teaching assistant. I thought the role of the instructor to teach the material, and the teacher assistants were just helping hands for assignments and grading. But often students come to office hours that really struggle with grasping concepts during lecture. This in turn makes it really hard for them to do the assignments, meaning I had to try my best to help a student understand the concepts.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Lily Zamanali","text":"When I walked into the classroom on my first day as a teaching assistant, I expected something like immediate, unwavering confidence to just wash over me. Confidence such that, even if I did not have the answers, I could still manage. Instead, that confidence was something I had to learn slowly over time.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Marco Gomez-Wong","text":"Being a TA is an insanely huge responsibility.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Melony Bennis","text":"Come into this with infinite patience, an open mind, and definitely set boundaries from the get go, no matter how awkward and difficult it may be.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Rachel Weaver","text":"I was, in essence, thrown directly into the current to either sink or swim. And even though it was a bit overwhelming to start, I think this is perhaps the best way to approach the job.","votes":0}
,{"topic":["Adjusting to TAing"],"author":"Stephen Read","text":"The human aspect of TAing was way more intricate and significant than the coding.","votes":0}
,{"topic":["Adjusting to TAing"],"author":null,"text":"I remember when I opened the email saying I had been hired as a TA. I was exhilarated and immediately relayed the information to my friends and family. But I had gotten blinded in the achievement of becoming a TA rather than focusing on the job. Becoming a TA was not really about myself so much as it was about the students.\n\nI should have been more concerned with learning rather than getting wrapped up in the emotional excitement of being a TA. I have found that the best TAs are the ones that understand their role the best. They understand when to keep quiet and when to get involved and help out a student. Instead, initially as a TA I was always the first to speak and intervene since “I am the","votes":0}
,{"topic":["Adjusting to TAing","Professionalism"],"author":"Rupali Vohra","text":"It can be difficult to remember sometimes that being a TA is a job. This probably means that a certain level of professionalism is expected.","votes":0}
,{"topic":["Adjusting to TAing","Professionalism"],"author":"Haley Bowler","text":"Learning how to be a good TA isn't something I was told how to do; I've had to figure it out as I've gone along.","votes":0}
,{"topic":["Adjusting to TAing","Professionalism"],"author":"Anonymous","text":"Every lab has one or two students who are super annoying for whatever reason.  With these students, you may not want to help them as much as other students.  This should go without saying, but remember it's part of your job to help all students and you just have to grin and bear it.  Don't avoid helping them just because they're annoying -- it's not fair to them or to other TAs.","votes":0}
,{"topic":["Adjusting to TAing","Professionalism"],"author":"Apoorva Arukumar","text":"It is important to maintain an aura of legitimacy.  Keeping control of a classroom, knowing when to check on students, making announcements properly, and having a well-run lab can all contribute to this.","votes":0}
,{"topic":["Adjusting to TAing","Professionalism"],"author":"Leila Kouame","text":"It is not necessary to always be the serious TA.  Allowing yourself to get in a laugh or two with a students can greatly relieve stress and make a student's day.","votes":0}
,{"topic":["Adjusting to TAing","Professionalism"],"author":"Chiara Sauvage","text":"You need to watch what you say, because anything can affect someone who sees you as more knowledgeable than them. It’s very easy to make someone feel bad even when you think you’re helping.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Nate Rathjen","text":"There were several aspects that surprised me – mostly relating to the sheer amount of time most of the TAing tasks required.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Andrew Norton","text":"TAing can take over your life (in a good-ish way) if you're not careful.  Create a schedule and stick to it, not necessarily to ensure that you provide at least *x* hours per week of work, but to ensure that you constrain TAing to *x* hours per week.  It is human nature to want to help people (some individuals find this desire stronger than others), but there will always be another student who needs help.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Casey Huang","text":"Compose an escape line.  You will go to a party where someone will say \"Hey! You're my TA!\"\n\nIt will be awkward.\n\nFiguring out your response ahead of time is a great idea. And then let me know what you came up with, because after 7 semesters, I still got nothing.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Sebastian Lerner","text":"It's totally okay to tell people that you are off the clock and they should leave.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Nate Rathjen","text":"The deluge of office hour visitors wasn’t entirely predictable.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Stephen Feldman","text":"Do what is required and do your best, but don't try to do everything.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Casey Huang","text":"Create a separate folder for Piazza emails [or change your Piazza account preferences to not send you email and check it online —Ed].  (This, in theory, works. What happened for me was I just forgot Piazza was ever a thing until my supervisor sent an angry email telling us to check Piazza.)","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Dominic Richie","text":"I've come to expect someone to say \"hey, you're my TA!\" when I'm in line at Bobo's or I'm shopping at Trader Joe's.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Sebastian Lerner","text":"Don't hang out in the stacks when you're not on the clock.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Andrew Norton","text":"Stick to your office hour schedule and leave when your time is up (staying \"5 minutes longer\" turns into an hour really easily). Create a scheduled time for Piazza and don't use it as a procrastination tool.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Cameron Blanchard","text":"Being a TA will require a lot of studying the material that you're helping teach.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Lina He","text":"There is not point in showing up to lab early.  Unlike being a student, showing up early doesn't mean you get to finish early.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work"],"author":"Ajay Patel","text":"Finding a balance between schoolwork and TAing is difficult, because there’s always another Piazza post to answer and another student that needs help. Keep your own schoolwork and the responsibilities of being a TA separate, regardless of whether one has abnormally more or less work than the other.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work","When there are too many students..."],"author":"Rupali Vohra","text":"I was in an environment where 20 students needed attention all at once. [...] Of course, I knew going into the job that I would have a lot of people who needed help at once. I think it is a little unreal, however, the exact magnitude of what being a TA is like until you actually experience it for yourself.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work","When there are too many students..."],"author":"CS 1110 Office Hour Tips document","text":"Don’t spend too much time with one person. Instead give them a few things to do work and then tell them to get on the queue again if they need help.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work","When there are too many students..."],"author":"Casey Huang","text":"You don't need to stay longer hours. There will be times when the queue is too huge to handle. You don't need to stay longer than your obligated office hours, and you don't need to help every student who will come up to you asking for help while you're trying to get your own work done.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work","When there are too many students..."],"author":"Alec Grieser","text":"When there is a hard lab, many students show up to office hours but the time for office hours is the same, so the amount of time that can be spent on each student is lower than usual.  But the lab is hard, so each students wants/needs more help than usual.  What to do then?\n\n(paraphrase: If you limit time with each student, you'll find a reasonable exception to that rule.)  Now that you have one exception to the rule, you'll start finding more edge cases.  [...] It ends up being much harder to say \"I'm sorry, but I have to go\" in real life than one might think.\n\nOne technique that other TAs have suggested is to limit the number of *questions* that people can ask rather than the amount of *time*.","votes":0}
,{"topic":["Adjusting to TAing","Amount of work","When there are too many students..."],"author":"Srija Tumu","text":"At first I did not know how long to spend on a particular problem while other are waiting to get help.\nI followed techniques taught in CS 2910, such as\ngiving them a task to do and ask them to get back in the queue if they have further questions\nand trying to answer the question without looking at their code.\nBy following these techniques, I stared to get a sense of how long I can spend on a person based on number of students in the queue.","votes":0}
,{"topic":["Adjusting to TAing","Other TAs"],"author":"Casey Huang","text":"Get to know your fellow TAs, both undergrad and grad. This is a major reason I stuck with TAing for way too long. There's a really great community there. Plan a potluck, throw a party, or organize a skydiving trip like I always meant to but never did. (Because sometimes, after grading an exam, all you really want to do is jump out of a plane.)","votes":0}
,{"topic":["Adjusting to TAing","Other TAs"],"author":"Bethany Connor","text":"You will learn as much or more in the first semester TAing than you did when you took the class (or at least that's what happened to me....sorry Bloomfield!).  There's nothing wrong with that and a good reason to ask the more experienced TAs questions.  They remember how it was when they were new.","votes":0}
,{"topic":["Adjusting to TAing","Other TAs"],"author":"Walter King","text":"If I could give a word of advice to the new TAs, I would say not to be afraid to ask for the help of another TA or a professor if you cannot remember something in the course content.  At times it can be difficult to find a particular bug in a student's code, but oftentimes a new set of eyes is all it takes to solve a problem.","votes":0}
,{"topic":["Adjusting to TAing","Other TAs"],"author":"Monica Kou","text":"Do not hesitate to ask for another TA's help.","votes":0}
,{"topic":["Adjusting to TAing","Other TAs"],"author":"Xhama Vyas","text":"I didn't realize how much time [the TAs would] end up spending together.  It's great because I've met one of my best CS friends that way, but also a challenge if someone's not necessarily your favorite person or if you disagree with the way another TA does things.","votes":0}
,{"topic":["Adjusting to TAing","Other TAs"],"author":"Xhama Vyas","text":"A huge shout out to my fellow [course name redacted] TAs for being just stellar in general.","votes":0}
,{"topic":["Adjusting to TAing","Other TAs"],"author":"Emily Zhou","text":"The best support system you have is your fellow TAs.","votes":0}
,{"topic":["Adjusting to TAing","Other TAs"],"author":"Frank Vasquez","text":"I was pleasantly surprised about was how sociable and friendly all of the other TAs were during down time in office hours.","votes":0}
,{"topic":["Adjusting to TAing","Other TAs"],"author":"Sara Inglis","text":"The other TA’s for your class are probably all smart stimulating people with diverse majors and interests, so get to know them.","votes":0}
,{"topic":["Adjusting to TAing","Preparation"],"author":"Steph Colen","text":"Do the homework ahead of time - even if you've already done it before! It'll help jog your memory and hopefully give you an idea of other ways students might approach the problem.","votes":0}
,{"topic":["Adjusting to TAing","Preparation"],"author":"Andrew Norton","text":"Attend TA meetings--don't blow them off, even if your professor is ok with you doing so. It's a great way to get a feel for how the class as a whole is doing, especially if grading guidelines for a course are vague.","votes":0}
,{"topic":["Adjusting to TAing","Preparation"],"author":"Apoorva Arukumar","text":"I really had to know the concepts well enough to explain them to a little child.  That's not to call UVA students little children, but more to say I had to know my material better than I learned it in class. [&hellip;] I made sure to go through all my old notes and lectures to make sure I was prepared.","votes":0}
,{"topic":["Adjusting to TAing","Preparation"],"author":"Michael Cooper","text":"It is invaluable to do the homework sets before office hours.  Even the material that was familiar to me would often have some phrasing of problem specification that I did not remember or did not anticipate.","votes":0}
,{"topic":["Adjusting to TAing","Preparation"],"author":"Anonymous","text":"I wish I had reviewed the [course redacted] material even more so that I could have been a more effective TA.","votes":0}
,{"topic":["Adjusting to TAing","Preparation"],"author":"Emily Zhou","text":"It is *so* important to try the homework assignments before office hours.\n\nThere is a difference between being prepared to answer questions about the course (all TAs have the theoretical background to do so) and being prepared to answer questions about the homework assignments for the course.  So be prepared and do the homework!","votes":0}
,{"topic":["Adjusting to TAing","Preparation"],"author":"Anne Springsteen","text":"I assumed that I would be able to pick out problems in students' code [but] many students were coming up with different approaches that I had not thought through. I learned that no matter how well I know Python, it is essential to be fully prepared for all labs and office hours. This involved\n\n- completing all the homework assignments,\n- brainstorming potential approaches students could take,\n- imagining problems they could face, and\n- reviewing the lecture slides.\n","votes":0}
,{"topic":["Adjusting to TAing","Preparation"],"author":"Ajay Patel","text":"TAing a class is almost like taking it again. Keeping up with the material is difficult because you do not go to lecture like a normal student yet still need to pay attention to the notes and know what is going on in class. This seems obvious, but with five other classes to worry about, it kind of slips your mind sometimes.","votes":0}
,{"topic":["Adjusting to TAing","Preparation"],"author":"Alyssa Porto","text":"There will be difficult times that you cannot prepare for and that is okay.","votes":0}
,{"topic":["Adjusting to TAing","Preparation"],"author":"Anonymous","text":"When unsure about a particular question I would sometimes show my uncertainty by acting nervous. The students who saw that treated me like my reasoning was flawed or completely incorrect for the rest of the semester. Doing the homework beforehand was a great way to avoid losing the trust of more students in this way.","votes":0}
,{"topic":["Adjusting to TAing","Preparation"],"author":"Shantanu Kelkar","text":"At the beginning of the semester I sometimes had to go back and review the class PowerPoints to relearn the material that I thought I knew very well. Later in the semester I switched to using notes from when I took the course, which accelerated the review process.","votes":0}
,{"topic":["Interacting with Students"],"author":"Emily Zhou","text":"Students, like all other people, perform better with encouragement and smiles.","votes":0}
,{"topic":["Interacting with Students"],"author":"Patrick Myers","text":"One of the best techniques I’ve found is asking questions. <q>What do you think is causing your program to crash? How might you be able to fix that?</q> This worked surprisingly well many times. Students who were initially lost were able to realize their error and correct it with little to no help.","votes":0}
,{"topic":["Interacting with Students","Not just subject matter experts"],"author":"Jim Roberts","text":"There should be an emphasis across the department made on individual problem solving, with TAs being told to only facilitate critical thinking and question answering such as \"How can I figure out what is causing my issue?\". This may be be too big of a culture shift for some groups of TAs to make right away, but hopefully over time this can be achieved.","votes":0}
,{"topic":["Interacting with Students","Not just subject matter experts"],"author":"Atallah Hezbor","text":"As a TA I feel that I am contributing to students’ attitudes towards computer science as well as their outlook on if the field is right for them.","votes":0}
,{"topic":["Interacting with Students","Not just subject matter experts"],"author":"Haley Bowler","text":"People will come to you with unrelated questions. People have come to me about what classes to take, why I decided to be CS major, what to do if they didn’t get into the major, etc. If I had to communicate this situation to new TAs I would tell them that they never have to answer questions that are unrelated to their subject, and that they definitely shouldn’t if they don’t feel comfortable doing so, but that it’s also kind of cool that people want to come to you for advice.","votes":0}
,{"topic":["Interacting with Students","Not just subject matter experts"],"author":"Bethany Connor","text":"Often the students are intimidated by the professors and come to the TAs because they feel more comfortable. While you shouldn't let them walk all over you, it is okay to act more casual in order to allow them to trust you and feel comfortable asking you questions. This is also a good way to get feedback as to how to the course is going to the professor.","votes":0}
,{"topic":["Interacting with Students","Not just subject matter experts"],"author":"Andrew Norton","text":"Know how to say \"no.\" I've gotten questions during office hours that have nothing to do with the course, but are just requests for help with general computer problems.  When office hours are empty, it can be tempting to help with these general problems, but you want to make it clear that this can't become a habit -- you don't want to be tech support for this student.","votes":0}
,{"topic":["Interacting with Students","Not just subject matter experts"],"author":"Divya Bhaskara","text":"It would have been nice to know how many tech support-esque questions we'd receive.  It would have been nice to receive guidance on how to answer these questions.  I've learned to redirect this type of question to someone else on the teaching staff if I don't know the answer.","votes":0}
,{"topic":["Interacting with Students","Not just subject matter experts"],"author":"Anthony Quach","text":"A lot of times the questions students ask aren’t just about CS, they’re also “what do I do if both my partner and I submitted when only one of us was supposed to” or “I accidentally submitted the wrong thing. Can I get a regrade?” Knowing how to improvise and respond to these types of questions is a big part of the job.","votes":0}
,{"topic":["Interacting with Students","After an explanation fails to teach"],"author":"(paraphrased by a TA from Wes Weimer)","text":"People learn differently (aurally, visually, learning by doing, etc.), so if someone doesn't understand your explanation of a certain topic, don't repeat yourself -- have backup explanations ready. Draw a picture, write code, or use a ridiculous analogy. Consider working from the bottom up (start with basics) or the top down (start with big picture).","votes":0}
,{"topic":["Interacting with Students","After an explanation fails to teach"],"author":"Cameron Blanchard","text":"Assuming they know everything from their previous classes confuses some students who don't remember most of the stuff they learned in 2150 and earlier.","votes":0}
,{"topic":["Interacting with Students","After an explanation fails to teach"],"author":"Michael Cooper","text":"Sometimes the most efficient or useful strategy in my mind was not intuitive or even incomprehensible for some of my students.  I learned to think adaptively, substituting new analogies and new methods of explanation when I saw that the students were confused.","votes":0}
,{"topic":["Interacting with Students","After an explanation fails to teach"],"author":"Nikhil Gupta","text":"My way of explaining things didn't work on everybody.  I tend to lean towards the visual teaching side, but not everybody responds to this.  Some people just needed to be given some reading to do, others had to talk through the problem with somebody, and some of them I still don't know the best way to teach.\n\nThink of different ways of handling questions and prepare various styles of solutions to commonly-asked questions.","votes":0}
,{"topic":["Interacting with Students","After an explanation fails to teach"],"author":"Madeline Watkins","text":"Sometimes the way in which I was explaining made no sense to the student.  It was extremely difficult to step back from how I had always thought about the problem and figure out a new way to explain it.  This got easier throughout the semester.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"CS 1110 Office Hour Tips document","text":"Actually listen to what their problem is. Try not to generalize and start explaining how to fix the most common problem.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"Rupali Vohra","text":"My listening skills have gotten infinitely better.  A big part of the job is hearing the entirety of a student’s question, understanding it, and then responding to it appropriately.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"Atallah Hezbor","text":"I discovered the differences in students’ expectations.  Some would simply want a pointer in the right direction and would then dive into the task independently, but some needed extensive explanation of the concepts and more detailed guidance.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"Xhama Vyas","text":"It's important not to make assumptions about students based on their skill level.  Some students that don't know that much off the bat end up being the strongest in the course and showing the most dedication and perseverance, and not all students that are super knowledgeable are snarky nerds.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"Rupali Vohra","text":"I think a big part of being a successful TA is knowing how to pick up on the type of personality a student has, and responding to it appropriately. Some students are sarcastic and appreciate dry humor, while others feel insulted if that approach is used. Some need baby steps and handholding while others feel like their intelligence is being insulted with such an approach. Some students are so stressed out that you can tell they are on the verge of tears.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"Jonathan Youssef","text":"Each person needs different informational guidance, put in different ways, spoken in different tones, presented at different rates, to arrive at the final conclusion—a conclusion they need to reach themselves.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"Peter Bahng","text":"It is easy to form a bias even at a subconscious level without making an effort not to do so.\n\nI found myself feeling bad for some of the students and wanting to go the extra mile to help them, just because they were connecting with me in the emotional sense [...] but I wouldn't want to give the same attention to students that just seemed not to care, even if that was based off of my own perception.  After realizing this, I made a conscious effort to treat each student equally.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"Cameron Blandford","text":"Some people ask for help, but sometimes you have to ask people if they need help.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"Leila Kouame","text":"Every student is unique, in how they communicate and learn and so asking the right guiding questions is a skill that takes time and experience to learn.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"Chaira Sauvage","text":"Be ready to comfort some students and remind them that they are capable of understanding and completing everything. A lot of the job is simply paying attention to how the students feel and raising their confidence to help them move forward.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"John Melloy III","text":"Sometimes the students, through no fault of theirs, do not understand the concepts in the same way I do, simply because people learn things in different ways. Which means it is my job to find a way to help them understand.","votes":0}
,{"topic":["Interacting with Students","Understanding each student"],"author":"Lisa Nguyen","text":"I’m used to helping out friends and it's easy to teach them because I knew them and how they learn. It can be much harder to deal with a large number of students you don't know.","votes":0}
,{"topic":["Interacting with Students","When your friends are in the class"],"author":"Jacki Morin","text":"If there is one thing I with I had been warned about, it is something I had never anticipated being an issue: my closest friends.  From day one, I had students texting me, calling me, even approaching me at social events to asks me questions about the class or request that I assign them to the project they wanted to work on.\n\nIt's always weird to deal with a friend approaching you about the fact that you never responded to their text message asking for help.","votes":0}
,{"topic":["Interacting with Students","When your friends are in the class"],"author":"Haley Bowler","text":"Some of your friends will think they have certain privileges. Giving certain students help that others don’t have access to is unfair. I think that having to act differently around people because you are doing this job can be uncomfortable, so it’s good to be prepared for it.","votes":0}
,{"topic":["Interacting with Students","When your friends are in the class"],"author":"Apoorva Arukumar","text":"I wish I had known how obnoxious and frustrating it can be when someone will constantly Facebook message me or pester me at the library asking for help when I'm trying to do my own work.","votes":0}
,{"topic":["Interacting with Students","When your friends are in the class"],"author":"Annie Springsteen","text":"I recommend making it clear to friends in your course that there are rules you must obey as a TA. I had three friends in [the course I TAed] this semester and I told them in the very beginning that I couldn’t help outside of office hours. I was also cautious about how I helped them in office hours because I didn’t want to give them more help than a regular student. Addressing these issues at the start of the semester and coming up with a plan on how to deal with them is the best approach.","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Casey Huang","text":"It is not okay to make a student cry. We all know CS is at least 90% frustration, and probably more so if it's a CS1 class. Be encouraging and tell them to take a break if they need to.","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Emily Zhou","text":"Don't ask the angry student across the table to repeat himself in the middle of his rant about TA incompetence.","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Atallah Hezbor","text":"I soon became aware that many students will put themselves down when they are encountering problems, and I had to find a way to provide help as well as be a source of encouragement.","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Leila Kouame","text":"At times students will be stressed and some of that frustration could get taken out on you as the TA.  Dealing with frustrated students is part of the job, and so always keep your calm and try not to take students' frustration personally.","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Atallah Hezbor","text":"I have heard complaints from students that a TA helped them but they did not find it helpful; however, TAs must also know how to exercise discretion and not provide too much help.","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Haley Bowler","text":"People will be mad at you. I didn’t realize how frustrated some people will get when you don’t tell them the answer. Sometimes people have tried to trick the answer out of me by asking things like “well how would you word this.”","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Atallah Hezbor","text":"Programming can sometimes be stressful, and in an environment where people discuss their progress, it can become easy for a student to feel behind or inadequate. It is a TAs job to not only provide help, but to provide encouragement when things aren’t going well.","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Casey Huang","text":"Take [a class that has a reputation for being hard]. You're a TA because you're smart and you're good at this stuff; but most of the people you'll be helping out will be the ones who are struggling (and therefore be experiencing something very different from what you did). It's a good idea to take [a hard class] so you'll realize how it is feeling stupid and helpless and so, so, so desperately dependent on outside-of-lecture help.","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Leila Kouame","text":"Although your goal is to complete our job and help students, don't do so at the expense of your own well-being.  If you fell as though a student is treating you disrespectfully, leave the situation and don't hesitate to ask a fellow TA to provide help to the student instead.","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Emily Zhou","text":"[…] My first mistake to think that the student was accusing me directly.  Actually, he was probably having a bad day and frustrated, took it out on us.  We should not respond in kind.  The right response to an angry student is to ask him to bring his concerns to the professor through either an appointment or anonymous feedback.","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Annie Springsteen","text":"When students asked for help, I replied with questions that made them think but also offered guidance. Often, students who were only looking for answers didn’t appreciate these questions. I didn’t want to annoy the students I was trying to help, but I knew that giving them what they wanted wouldn’t be fair or appropriate.","votes":0}
,{"topic":["Interacting with Students","Frustrated Students"],"author":"Anthony Quach","text":"When they have been working for hours and are clearly frustrated it’s hard not to feel for them. In these times it’s important to maintain composure, stay disciplined, and not just hand them the answer. Instead lead them to the answer by responding to their questions with questions of your own. Few things are more satisfying than when a student gets an “aha!” moment because of questions you asked.","votes":0}
,{"topic":["Interacting with Students","Hard Questions"],"author":"Casey Huang","text":"It's okay to say you don't know the answer to something.","votes":0}
,{"topic":["Interacting with Students","Hard Questions"],"author":"Stephen Feldman","text":"Be honest if you don't know the answer to a question.","votes":0}
,{"topic":["Interacting with Students","Hard Questions"],"author":"Casey Huang","text":"If you really can't figure it out, don't be afraid to ask another TA or post on Piazza.","votes":0}
,{"topic":["Interacting with Students","Hard Questions"],"author":"Koleman Nix","text":"I wish I had known how frustrating it is to give a bad or unsatisfying answer to a question.","votes":0}
,{"topic":["Interacting with Students","Hard Questions"],"author":"Xhama Vyas","text":"TAing isn't you knowing all the answers, but just figuring out a problem more quickly than the student.","votes":0}
,{"topic":["Interacting with Students","Hard Questions"],"author":"Madeline Watkins","text":"It was extremely hard ot say \"I'm sorry, I don't know,\" but I strongly encourage future TAs to do so if they don't know an answer.","votes":0}
,{"topic":["Interacting with Students","Hard Questions"],"author":"Jamie Tudor","text":"Nobody knows all the right answers.  Being able to admit when you don't know something demonstrates that your ego is not wrapped up in being right all the time.  Implicitly, it says that their ego shouldn't be either.  Having a student ask you a question, to which you don't know the answer, gives you a great opportunity to discover the answer together.","votes":0}
,{"topic":["Interacting with Students","Hard Questions"],"author":"Anonymous","text":"Once a pair of students asked me their question, clearly frustrated that they did not understand what they were doing. When I was unable to understand their question or effectively help in anyway, I walked away to ask another TA in my lab. Behind me, I heard one of the students mumble to the other, “Ugh, that TA has no idea what (he/she)’s talking about.” Half of me wanted to yell at them for being so apparently rude, and the other half to turn around, laugh, and agree that I had no idea what I was doing most of the time. However, I knew neither of these would help the situation at all so I continued getting the other TA and smiled through the situation.\n\nFor the rest of lab, and a few days after, I felt like a failure. No matter how much someone tells you to not take it personally, you will. And then you will learn to stop taking it personally. TAing is a learning experience that you must go through on your own to truly be an effective TA.","votes":0}
,{"topic":["Interacting with Students","Hard Questions"],"author":"Caroline McNichols","text":"It’s impossible to predict what weird bug that one kid will have, and therefore impossible to be taught the solution in advance. I thought that I would magically have all the answers once I became a TA. It turns out that I’m just learning how to be better at solving the problems rather than knowing the solutions.","votes":0}
,{"topic":["Interacting with Students","Hard Questions"],"author":"Devon Yi","text":"Just as many of the previous TAs mentioned, admitting when I didn’t know something and asking another TA for help was okay, and the students probably ended up trusting me more because I was able to do so; however, it would’ve been nice to know that occasionally messing up/being wrong was okay (e.g. once during office hours, students were doing the test from last semester, and I misread the question so confirmed the wrong answer).","votes":0}
,{"topic":["Interacting with Students","Hard Questions"],"author":"Toshali Randev","text":"Being a TA is not equivalent to being an instructor—it is okay for you to not know the answer to something.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Casey Huang","text":"There will be someone whose education you care more about than they do. Here will probably be someone who's doing really badly, asking all the wrong questions, flunking exams, and not putting in any effort to do better. You're a TA, not your job to fix 'em.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Nate Rathjen","text":"Students expected my help to be a “magic bullet”. Given that I am TAing an upper-level CS class I expected the students to do a lot of troubleshooting themselves before coming to me as a last resort. It became fairly clear early on in the project timeline this would not necessarily be the case.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Haley Bowler","text":"All incoming TAs should be prepared to say no to people. You can say no if someone obviously just there for an answer.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Nicholas Langemeier","text":"Say no, and then direct students to a section in the book, a site online, or some other resource.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Casey Huang","text":"Have a backbone. There will always be that one kid who's a [...] reincarnation - the one who INSISTS you walk them through the homework, and when you tell them to think for themselves, they pop back on the queue and ask another TA; or the student who's too busy playing Candy Crush while you're sitting there trying to debug their awful code ... you'll know 'em when you see 'em.\n\nDon't let them walk all over you and, especially towards the later homeworks, tell them that they need to work it out on their own. They can talk to you again when they've made progress.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"CS 1110 Office Hour Tips document","text":"Don’t just tell them what’s wrong, make sure they understand why it’s wrong. We are teachers first, troubleshooters second.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Tahiya Salam","text":"A lot of students' confusion stems from either their lack of having thoroughly evaluated the problem or their inability to understand or follow directions.  [...] It's more valuable for the students to figure things out on their own.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Peter Bahng","text":"Be prepared for those students that want nothing but the solution out of you.  They can be difficult to handle, but I found it worked to say “I think that is more than enough information to successfully solve this problem.”","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Kamille Foster","text":"Some of the students just don't care.  They just want to get by as painlessly as possible and will try to exploit any loophole and use any shortcut they can find and, unfortunately, the shortcut is usually their TAs.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Anthony Quach","text":"I was impressed by the students and their willingness to learn. Having been warned about students fishing for answers at office hours, I expected to see a lot more of it. To my pleasant surprise, the overwhelming majority of students that I interacted with were there attempting to actually learn and understand the material and assignments.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Lily Zamanali","text":"If you learn to say “no,” good job! Refusing to help a student inappropriate situations is a great first step, but first steps need second steps. Literal steps. So say “no” and walk away.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Sara Inglis","text":"Some people didn’t even have a problem, they just needed you to slowly read the directions aloud to them, because they would skip over things if they read it themselves.","votes":0}
,{"topic":["Interacting with Students","Needy Students"],"author":"Toshali Randev","text":"The fact that a student chose to start their homework an hour before it’s due is not your fault, nor is it your problem.\nThe job of a TA is to be an assistant, a helper, maybe even a friend, but not a scapegoat and definitely not a replacement for the professor or CAPS. It is completely okay to refer the student elsewhere if you feel like their problems are too big for you to handle.","votes":0}
,{"topic":["Interacting with Students","Answering Questions"],"author":"Robert Mina","text":"The hardest part of the job isn't knowing how to solve all the problems but having the patience to let the students solve them themselves (as opposed to doing it for them).","votes":0}
,{"topic":["Interacting with Students","Answering Questions"],"author":"Casey Huang","text":"Show them how you'd go about finding out the answer - google it, stack overflow it, look it up in the syllabus. They'll learn how to answer stupid questions on their own, and you'll be making yourself more approachable by removing the initial intimidation of \"ermagerd its a ta.\"","votes":0}
,{"topic":["Interacting with Students","Answering Questions"],"author":"Andrew Norton","text":"Learn how to postpone a question.  Students have a tendency to ask rapid-fire questions about problems that aren't causally related.  This can be frustrating because you're dealing with a disorganized thought process (or, sometimes, a deep confusion over what errors are related).  Keeping a student on track by saying \"we'll get to *question 2* after discussing *question 1*\" is invaluable.","votes":0}
,{"topic":["Interacting with Students","Answering Questions"],"author":"Joseph Scott","text":"One of the best ways to help someone is to ask them questions that lead them in the right direction, rather than telling them directly what they are doing right/wrong.","votes":0}
,{"topic":["Interacting with Students","Answering Questions"],"author":"Ben Matthews","text":"Ask the student to explain their code and problem before jumping to a solution is a useful teaching tool. You will better understand the problem and have time to formulate a response, the student will understand what they have done fully (solving other problems in the code), and the student will often come to the solution in the process.","votes":0}
,{"topic":["Interacting with Students","Answering Questions"],"author":"Haley Bowler","text":"Listening is just as important as talking because everything someone says is a clue about what they do and don't know and what they expect from me.","votes":0}
,{"topic":["Interacting with Students","Answering Questions"],"author":"Joseph Scott","text":"Help them get in the habit of reading official docs. Don’t just tell them what the method is that does such and such, look it up online with them.","votes":0}
,{"topic":["Interacting with Students","Answering Questions"],"author":"Steph Colen","text":"It might be tempting to just give kids the answers, especially when they've been struggling for a while, but do your best not to use their computers at all and not just tell them the solution. Try to guide them to the solution with pointed questions, or dictate what to type while debugging - many of them will learn it better if they're the ones actually doing the work!","votes":0}
,{"topic":["Interacting with Students","Answering Questions"],"author":"Leon Zhan","text":"Something Rupali does well that I am still working on is just telling the students \"I think you can figure that out\" or \"That's your job to figure out.\"","votes":0}
,{"topic":["Interacting with Students","Answering Questions"],"author":"Maria Scheitzer","text":"I took an amazing class in which we practiced and discussed the benefits of active listening. This really helped me understand what problem the student was facing.","votes":0}
,{"topic":["Grading"],"author":"Andrew Norton","text":"Learn and use Bash.   There's a lot of repetitive tasks in grading, especially for intro courses--for instance, unzipping files, compiling a program, and possibly feeding in sample input.  It's so much easier to spend 10 minutes writing a bash script for the whole assignment to save a minute per assignment.","votes":0}
,{"topic":["Grading"],"author":"Andrew Norton","text":"I'm always concerned that I'm not grading my students' assignments the same way as all the other TAs, or that I'm giving too much/little help during office hours.  Just by meeting up and talking with the other TAs, even if you don't directly discuss grading standards, etc, will give you a better understanding of the mindset of everyone else.","votes":0}
,{"topic":["Grading"],"author":"Andrew Norton","text":"Use Google Forms to make things easy on yourself, especially for lab TAs.  A well-designed Google form can make it very easy for you to assign grades.  In effect, you're crowdsourcing the initial steps of grading by pushing the organization of data onto the students.","votes":0}
,{"topic":["Grading"],"author":"Lina He","text":"Grading guidelines sometimes leave a lot of decision making to the TAs.  Be consistent when grading and don't worry too much about the small details.","votes":0}
,{"topic":["Grading"],"author":"Kelsey Hewett","text":"I was surprised how much time and energy goes into grading assignments and exams.  I had never quite realized how long it can take to grade 130 exams or papers.  After spending over 4 hours grading the first midterm, I had a lot more respect for professors that are still willing to create 4+ page exams anyway.","votes":0}
,{"topic":["Interacting with your supervisor","They are your bosses, but..."],"author":"Rupali Vohra","text":"It is especially weird when you know the professors you are TAing for as a professor before you know them as a boss.","votes":0}
,{"topic":["Interacting with your supervisor","They are your bosses, but..."],"author":"Casey Huang","text":"Talk to the professors you TA for, and other professors too. There's a lot to learn from them, and that's partially why you're TAing, right? Strike up a conversation. Ask Sherriff about Samantha, or ask Bloomfield about how he feels about judging errors in ICPC (and let him know that he's been using Linux for longer than you were alive, he loves that). Works 100% of the time.","votes":0}
,{"topic":["Interacting with your supervisor","They are your bosses, but..."],"author":"Michelle Wang","text":"I was shocked to find that Professor [name redacted] doesn't provide any material for TAs.","votes":0}
,{"topic":["Interacting with your supervisor","They are your bosses, but..."],"author":"Anthony Quach","text":"It was cool seeing how much the CS professors trusted their TAs and how often they sought advice from them, often modifying class material based on their feedback. I came in expecting the relationship between professors and TAs to resemble that of bosses and employees but was instead greeted with a colleague type treatment.","votes":0}
,{"topic":["Interacting with your supervisor","They are your bosses, but..."],"author":"Devon Yi","text":"I really enjoyed the community the TAs in my class had, and was grateful that I was able to get to know the professors more (to be honest I originally thought Luther was a little intimidating).","votes":0}
,{"topic":["Interacting with your supervisor","They are your bosses, but..."],"author":"Lily Zamanali","text":"I also learned about the “Turtle Songs of North America” by They Might Be Giants. The Eastern Fighting Turtle will DECIMATE you. AVOID AT ALL COSTS.","votes":0}
,{"topic":["Interacting with your supervisor","They are your bosses, but..."],"author":"Marco Gomez-Wong","text":"TAs often have to make policy and grading calls based on their own judgement and not just regurgitations of a professor’s.","votes":0}
,{"topic":["Interacting with your supervisor","They are your bosses, but..."],"author":"Marissa Lee","text":"I was a little stressed during the time a student came to me, frustrated with a problem the professor could not solve during his office hours. I figured it out in the end, but it took a lot of time. I brought up the matter during CS 2910 class but I am still not completely sure on how to handle problems that come to me at the last resort.","votes":0}
,{"topic":["Interacting with your supervisor","They are your bosses, but..."],"author":"Rachel Weaver","text":"Being a TA introduces you to a community of other TAs but also the Professors. You become more involved and engage in deeper conversations about the department, course materials, the field of education in general, etc.","votes":0}
,{"topic":["Interacting with your supervisor","Ask questions"],"author":"Jim Roberts","text":"Don’t be afraid to ask for help (and then actually do it).  This has actually been said or implied every time that I have TA’d but I didn’t take it to heart and try to do it until later.","votes":0}
,{"topic":["Interacting with your supervisor","Ask questions"],"author":"Rupali Vohra","text":"Another big portion of being a TA has nothing to do with interacting with students, but has a lot to do with interacting with the professors of the course and fellow TAs. [...]  It is hard to ask questions because everyone else already seems to know what is going on, and it can be unclear which questions should be addressed to whom. I often felt like I was bothering both professors and other TAs by asking potentially obvious questions, but at the same time I knew that I had to ask the questions since the answers to those questions affected how I interacted with students, and that was an important interaction to get correct.\n\n[When asked, her supervisors both expressed appreciation for her habit of asking lots of questions. —Ed]","votes":0}
,{"topic":["Interacting with your supervisor","Ask questions"],"author":"Walter King","text":"If I could give a word of advice to the new TAs, I would say not to be afraid to ask for the help of another TA or a professor if you cannot remember something in the course content.  At times it can be difficult to find a particular bug in a student's code, but oftentimes a new set of eyes is all it takes to solve a problem.","votes":0}
,{"topic":["Interacting with your supervisor","Ask questions"],"author":"Leila Kouame","text":"It may seem like some colleagues are more approachable than others but we all love the field and love talking about it so you should not be afraid to ask questions of someone who miht know more than you.","votes":0}
,{"topic":["Interacting with your supervisor","Ask questions"],"author":"Caroline McNichols","text":"I know it now, but I wish someone had told me it’s normal to not have all the answers. I wish someone had told me it is okay to ask for help.","votes":0}
,{"topic":["Interacting with your supervisor","Ask questions"],"author":"Claire Veasey","text":"When I started I knew that I did not fully understand all of the topics and I figured that I would just pick up on it as I went, but I missed one of the major points of being a TA – asking questions and asking for help.\n\nAt first I was embarrassed to ask questions because I felt like I should already know all the things that I was unsure and nervous about. It’s intimidating coming in as the newbie – you don’t know exactly what’s going on, and to be honest you’re still getting used to knowing all of the material. I did not want to be seen as the “worst TA” who never knew what is going on.\n\nI wish I had asked more questions within the first half of the semester so I could have done a better job throughout the rest of the semester. I eventually got my answers even if I didn’t specifically ask, but it took a lot longer than just being brave and asking a question to begin with.","votes":0}
,{"topic":["Other Advice"],"author":"Anonymous","text":"Don't pull up your e-mail in front of a lecture hall of students. [...] You will be embarrassed. It's also probably a good idea to keep talking about drinking [etc.] to a minimum when in front of a lecture hall.","votes":0}
,{"topic":["Other Advice"],"author":"Stephen Feldman","text":"Enjoy every moment of your TA experience – you may remember it fondly one day.","votes":0}
,{"topic":["Other Advice"],"author":"Casey Huang","text":"Don't freak out if you mess up - it happens to all of us. For example, I [examples redacted]","votes":0}
,{"topic":["Other Advice"],"author":"Jackie Morin","text":"You get out of the experience what you put in.  If you want to give a guest lecture or create a new assignment or even modify an existing one, ask your professor.  It could be a huge help to your professor, and an awesome new experience for you!","votes":0}
,{"topic":["Other Advice"],"author":"Casey Huang","text":"You do not need to TA the same class for 7 semesters.","votes":0}
,{"topic":["Other Advice"],"author":"CS 1110 Office Hour Tips document","text":"Don’t overthink it.","votes":0}
,{"topic":["Other Advice"],"author":"Casey Huang","text":"Avoid Thornton Stacks when you're not TAing. You will be bugged for help. You will get no work done.","votes":0}
,{"topic":["Other Advice"],"author":"Casey Huang","text":"You can order a pizza from Thornton Stacks. But eating → extra saliva → spitting all over students while you talk. So while in theory this is a great idea, you should probably bring a facemask with you if you plan on ordering a pizza during office hours.","votes":0}
,{"topic":["Other Advice"],"author":"Monica Kou","text":"The mother of a student in the class I was TAing for approached me during office hours to ask for help on behalf of the student.  I do not believe this situation arises frequently, but I would suggest being prepared for parents or friends of students coming to office hours for help.","votes":0}
,{"topic":["Other Advice"],"author":"Emily Zhou","text":"First rule of office hours: focus on the student you're helping.  Do not help other students along the way.","votes":0}
,{"topic":["Other Advice"],"author":"Anne Springsteen","text":"I planned my review lessons before each lab, but I usually forgot some of my plans whenever I started talking. I learned there’s a big difference between explaining a problem to one student compared to 45.","votes":0}
,{"topic":["Other Advice"],"author":"Rachel Weaver","text":"I had the opportunity to give a lecture while the professors were gone at SIGSCE, which was an experience that helped to shape and form me as a TA. I would recommend this to any incoming TA, whether they think they are interested in","votes":0}
]
